### ISSUE TITLE
Modify default log to be log-settings.json

### ISSUE THREAD

**Issue by drew2g** [koenrad/android-style-logging#2]
No more 2 line import; also - eslint doesn't like the hacky one line way so there's that

EsLint DESPISES 
```
const Log = require('android-style-logging');
const log = new Log({ conf: require('../log-settings.json') });
```

make it

```
const Log = require('android-style-logging');
const log = new Log();
```

and log-settings.json will still be defaulted and if it doesn't exist then create it

**Comment by koenrad** [comment]
I have implemented a [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) `rc` file. You can create an `rc` file with your settings and place it in your project directory ( `.androidstyleloggingrc` ). 

You can still pass in a config object if you want to, to keep backward compatibility and multi instance capability.

e0baf69d51332954846c7976d7142eb70974999c closes this issue.
